// mensaje.js
const mensajes = [
    "🙌🙌🙌🙌🙌🙌🙌🙌\nCompro Compro Compro\n\nMLC a 220\nUSD a 245\nEuros a 245\nLo busco a su casa\nLo pago en efectivo\n🙌🙌🙌🙌🙌🙌🙌🙌",
    "♻️♻️♻️♻️♻️♻️♻️♻️♻️♻️♻️\n_COMPRO 💳 MLC A 220_\n*_COMPRO 💸USD A 245*_\n_*COMPRO 💶 EURO A 245*_\n\n💰*PAGO EN EFECTIVO*💰\n*CUALQUIER CANTIDAD*\n\n*+53 55806085* 📞",
    "⚠️✔️⚠️✔️⚠️✔️⚠️✔️⚠️✔️\n🚦 *OFERTA ESPECIAL* 🚦\n🔥🔥 *NUEVOS PRECIOS*🔥🔥\n\n          *R E M E S A S*\n*X 100 🇺🇸 recibe 23500 cup 🇨🇺*\n*X 100 🇺🇸 recibe 100 mlc 🇨🇺*\n*X 110 🇺🇸 recibe 100 USD 🇨🇺*\n*_COMPROO💯💯_*\n💳 *Mlc*⚡️ *220* 💳\n💵 *USD*⚡️ *245*💵\n💶 *Euro*⚡️ *245*💶\n🇨🇦 *D.canadiense* *130*🇨🇦\n*_TODO SERVICIO  SE REALIZA  ✅️ PRESENCIAL [Gerona-La fe]_*\n\n*_PARA TODOS MIS CLIENTES SABEN Q TIENEN MEJORES OFERTAS CON SERVICIO HASTA LA PUERTA DEL HOGAR_*\n\n*_🍱SERVICIO DE COMBOS 🍱_*\n🥩🍖🍗🍚🍤🥗🥣🧀🥔\n*TENEMOS LAS MEJORES OFERTAS EN COMBOS DE COMIDA  PARA TODA LA FAMILIA PINERA*\n🥬🥦🫘🍔🥩🥓🍖🍗🧀🍞\n\n*CON DIVERSAS OFERTAS DE PRECIOS A PAGAR EN EE.UU..🇺🇲*\n\n*✳️VIA ZELLE O CASHAP✳️*\n*🏷💵_160*\n*🏷💵_200*\n*🏷💵_240*\n*🏷💵_280*\n*🏷💵_300*\nETC......🫡\n🇨🇺*_TAMBIEN TENEMOS LA OPCION  DE PAGO EN CUBA_*🇨🇺\n\nATRAVÉS DE :👇🏾\n*_●MLC_*\n*_●USD_*\n*_TENEMOS DOMICILIO LIBRE DE COSTO ALGUNO_# 🚚\n⚜️*_PRESENCIAL_*🙋\n✔️ *SEGURIDAD Y EFICACIA*✔️\n🙏🏽💥 *LABORAMOS PARA SATISFACER A NUESTROS CLIENTES*💥🙏🏽\n⚠️✔️⚠️✔️⚠️✔️⚠️✔️⚠️",
    "📯📬📌🤍📯📬📌🤍📯📬\n\n*CAMBIO ♻️ USD 💳 X MLC* 💵\n《《Yo tengo el USD 》》\n🎃🍁🎃🍁🎃🍁🎃🍁🎃🍁🎃\n📬 🇺🇸 *REMESAS ♡ EE.UU*🇨🇺 📬\n‼️ _No existe límite de depósito ni de pago_ ‼️\n🏦 *TARIFAS* 🏦\n*100* 🇺🇸《recibe👉🏼 *23500cup* 🇨🇺\n*100* 🇺🇸《recibe👉🏼 *100mlc* 💳🇨🇺\n*110* 🇺🇸《recibe👉🏼 *100usd* 💵🇨🇺\n🍎🥡🍎🥡🍎🥡🍎🥡🍎🥡🍎\n*OFERTAS DE COMBOS🍱 MIXTOS DE COMIDA CON* :\n🔖 Domicilio gratis hasta su casa\n🔖Precios accesibles\n🔖 Variedad en ofertas\n🔖 Higiene y calidad\n🏷️ *PARA MIS CLIENTES FIJOS (VIP)🌟 MEJORES OFERTAS Y DESCUENTOS* 🫶🏼\n🏷️ *TRATO PRESENCIAL 🤲🏼 CONFIANZA Y SEGURIDAD* 🫂\n🏷️ _*Gracias x las buenas recomendaciones les deseamos magnífico día*_ 🌚🌞💫📯📬📌🤍📯📬📌🤍📯📬",
    "🇺🇸🇨🇺  *OFERTA DE REMESAS Y COMBOS DE COMIDAS* 🇺🇸🇨🇺\n➡️ *100 USD* 🇺🇲 - *23500 CUP* 🇨🇺\n➡️ *100USD 🇺🇸 - 100MLC* 🇨🇺\n➡️ *110USD 🇺🇸 - 100USD* 🇨🇺\n*Para mis clientes fijos tengo mejores ofertas, al igual q para la compra de divisas. No tenga pena y pregunte* \n*COMPRO DIVISAS*\n*MLC*- *220*\n*USD*- *245*\n*EUROS*- *245*\n*CANADIENSE*- *130*\n‼️ *PARA SABER LAS OFERTAS DE LOS COMBOS DE COMIDA PASE AL PV* ‼️\n *Link de grupo de WhatsApp:*\nhttps://chat.whatsapp.com/L1frnLZTSykG2JTqZnnVk9\n*TRATO PRECENCIAL en toda la Isla de la juventud*",
    " *OFERTAS DE REMESAS ACTUALES*\n*100 USD x 100 MLC*\n*110USD x 100 USD*\n*100 USD x 23500 CUP*\n*TAMBIÉN SE PUEDEN ENVIAR CANTIDADES MENORES DE 100 !!!*\n*RECIBIMOS POR*:\n*ZELLE*\n*MAZA* \n*SEIS*\n*CASHAPP* \n*SIEMPRE HAY MLC!!!*\n⚠️ *_TODOS LOS PAGOS A SU FAVOR_*",
    
];

module.exports = {
    mensajes
};
